version: 2
jobs:
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=${CIRCLE_TAG}
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/

  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: packaging
          command: apt update && apt install -y wget build-essential git libz-dev clang
      - run:
          name: install deps
          command: ./clone-all-the-things.sh
      - run:
          name: pwd?
          command: pwd
      - run:
          name: Greeting
          command: ./make.sh
      - store_artifacts:
          path: /root/project/daydreamer
          destination: /daydreamer
      - persist_to_workspace:
          root: /root/project
          paths: daydreamer
workflows:
  version: 2
  main:
    jobs:
      - build
  release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+$/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+$/
