version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: packaging
          command: apt update && apt install -y wget build-essential git
      - run:
          name: install deps
          command: ./clone-all-the-things.sh
      - run:
          name: setup env
          command: wget -O- https://srv2.elangley.org/~edwlan/sbcl-static.tgz|tar vzx 
      - run:
          name: pwd?
          command: pwd
      - run:
          name: Greeting
          command: ./make.sh
