version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: pwd?
          command: pwd
      - run:
          name: setup env
          command: wget -O- https://srv2.elangley.org/~edwlan/sbcl-static.tgz | tar vzx 
      - run:
          name: pwd?
          command: pwd
      - run:
          name: Greeting
          command: ./make.sh
