version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: packaging
          command: apt update && apt install -y wget build-essential git libz-dev clang
      - run:
          name: install deps
          command: ./clone-all-the-things.sh
      - run:
          name: pwd?
          command: pwd
      - run:
          name: Greeting
          command: ./make.sh
      - store_artifacts:
          path: /root/project/daydreamer
          destination: /
